project:
  type: website

website:
  title: "A few notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dcjohnson24
format:
  html:
    theme: cosmo
    css: styles.css



